#!/usr/bin/env node
const addTask = require('./commands/add.js');
const deleteTask = require('./commands/delete.js');
const { list } = require('./commands/list.js');
const completeTask = require('./commands/complete.js');
const helpers = require('./commands/helpers.js');

const command = process.argv[2];
const task = process.argv[3];
const id = process.argv[3];
const allTasks = helpers.getAll();

let result;
switch (command) {
  case 'add':
    result = addTask(task, allTasks);
    break;
  case 'list':
    result = list(allTasks);
    break;
  case 'complete':
    result = completeTask(id, allTasks);
    break;
  case 'delete':
    result = deleteTask(id, allTasks);
    break;
  default:
    result = 'Command not recognized';
}
console.log(result);
